version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy-docker
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user-docker
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed-docker
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend-docker:local
